### ISSUE TITLE
Notify reviewers of requested reviews through Slack

### ISSUE THREAD

**Issue by PombeirP** [status-im/status-github-bot#4]
### User Story

As a developer, I want to have clear visibility of when a pull request review is asked from me. Pull request reviews sometimes fall through the cracks due to the volume of emails/GitHub notifications.

### Description

A better way to address this issue would be to leverage the new GitHub bot (written on the [Probot framework](https://probot.github.io/)) to [listen to PR comment events](https://developer.github.com/v3/issues/events/) for a specific command (e.g. `/review @PombeirP @divan`), and then act on it by [telling GH to create the review request](https://developer.github.com/v3/pulls/review_requests/#create-a-review-request), and notifying the respective reviewers [on Slack](https://github.com/status-im/status-github-bot/blob/master/scripts/greet-new-contributor.js#L73) (either through a DM or a mention on a given room).

Since GitHub user names don't necessarily match Slack user names, the bot needs to use the cache held in `index.js`.

Documentation for the bot is available in the [wiki](https://wiki.status.im/GitHub_bot).

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x2cf16a6b89bd61356eec33ff42a86107fc71f8d555c2bdcd1954e2e610cd9d43](https://etherscan.io/tx/0x2cf16a6b89bd61356eec33ff42a86107fc71f8d555c2bdcd1954e2e610cd9d43)

**Comment by martinklepsch** [comment]
@PombeirP I'd be happy to work on this. One question though: you suggest that a user writes `/review @user` to request a review. This will allow anyone to request reviews not just collaborators. I assume this is intentional & wanted? 

Also I'm thinking it might be nice to split it into two distinct actions:
- create review request using `/review @user`
- listen for newly created review requests and notify users

This way review requests which have been created using the regular GitHub UI will also trigger Slack notifications.

**Comment by PombeirP** [comment]
@martinklepsch that's great, looking forward to your PR!

Yeah, you're right that it makes sense to create two event listeners (one for review comments and another for review requests). I think for now we can allow anyone to request a review (keeping in mind that we'll be able to tighten security at any point by executing only if the comment originates from a repo contributor).

**Comment by martinklepsch** [comment]
@PombeirP given the issue that [Github Apps currently cannot create Review Requests](https://github.com/probot/probot/issues/336#issuecomment-353247075) I'd like to step back a bit and reconsider the to-be-solved problems, before we move ahead with a non-app-user token and all that. 

As I understand it this issue is about solving two problems: 

1. Allow users which don't have write-access to the repository to create review requests
2. Make sure people who are assigned as reviewers are notified/reminded of open review requests

Solving **1)** is a little harder due to the Github App restrictions. Also parsing a comment, which is the suggested way of doing this as per this issue, is probably error-prone and somewhat complex to get right (thinking of edits and other mentions in the comment which might not be intended as reviewers).

Because of that I'd like to suggest to only move forward with **2)** for now and wait to see if **1)** is actually critical or if it could maybe also be solved by clever use of labels and/or reminders to assign reviewers to open PRs. 

#### Specific steps to solve **2)**:

1. We implement a bot that sends slack messages to a given user whenever they are assigned as reviewer
2. We send reminders about open reviews for each user a few times a week. 

Those could be created w/ bounties, from my work in #14 I believe there should be no blockers.

An idea to solve **1)** without getting into the user token/comment parsing problem: each project could have an "owner" that will be notified whenever a PR without reviewers exists. Then that owner steps in and assigns reviewers as they see fit.

**Comment by PombeirP** [comment]
1. is not really a requirement, just a potential side effect, so we don't want to do anything to support that specifically.
I guess the most valuable part of #4 is to have reviewers be pinged in Slack once a review is requested (maybe DM will end up being best, to avoid having the `#status-probot` channel becoming too noisy), so we can go with that.
